services:
  databases:
    image: mysql/mysql-server:latest
    container_name: localbase
    restart: always
    command: ['--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      LANG: C.UTF-8
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
